// Number of Company owned Devices that are Compliant or Not Compliant summarized by OS Platform
IntuneDeviceComplianceOrg
| where todatetime(LastContact) > ago(30d)
| where ComplianceState == "Not compliant" // Change to "Compliant" if you want to list only Compliant Devices
| where OwnerType == "Company"
| summarize arg_max(TimeGenerated, *) by DeviceName
| project ComplianceState, DeviceName, LastContact, OSDescription, OS
| summarize count(DeviceName) by OSDescription