// Number of Successful Enrollments by OS
// See here: https://github.com/rod-trent/SentinelKQL/blob/master/IntuneCountofSuccessfulEnrollmentsbyOS.txt
IntuneOperationalLogs 
| where OperationName == "Enrollment" and Result == "Success"
| extend OS = tostring(todynamic(Properties).Os
| summarize count() by OS

// Failed enrollments
IntuneOperationalLogs 
| where OperationName == "Enrollment" and Result == "Failed"
| extend OS = tostring(todynamic(Properties).Os
| summarize count() by OS
